name: Check Pull Format

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  # This workflow closes invalid PR
  close_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Close PR if it is not pointed to dev branch
        if: github.event.pull_request.base.ref != 'dev'
        uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post an issue comment just before closing a pull request.
          comment: "Invalid PR to `non-dev` branch `${{ github.event.pull_request.base.ref }}`."

  pull_format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    continue-on-error: true

    steps:
      - name: Checkout
        continue-on-error: true
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Adjust to your preferred version, or use a matrix for multiple versions.

      - name: Install Black
        run: pip install "black[jupyter]"

      - name: Run Black
        run: black .

  # Dependabot job (dependency update configuration)
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Dependabot
        run: |
          echo "version: 2" > .github/dependabot.yml
          echo "updates:" >> .github/dependabot.yml
          echo "  - package-ecosystem: \"pip\"" >> .github/dependabot.yml
          echo "    directory: \"/\"" >> .github/dependabot.yml
          echo "    schedule:" >> .github/dependabot.yml
          echo "      interval: \"daily\"" >> .github/dependabot.yml
          echo "    commit-message:" >> .github/dependabot.yml
          echo "      prefix: \"deps\"" >> .github/dependabot.yml
          echo "    versioning-strategy: \"increase\"" >> .github/dependabot.yml
          echo "  - package-ecosystem: \"npm\"" >> .github/dependabot.yml
          echo "    directory: \"/\"" >> .github/dependabot.yml
          echo "    schedule:" >> .github/dependabot.yml
          echo "      interval: \"daily\"" >> .github/dependabot.yml
          echo "    commit-message:" >> .github/dependabot.yml
          echo "      prefix: \"deps\"" >> .github/dependabot.yml
          echo "    versioning-strategy: \"increase\"" >> .github/dependabot.yml
